---
- name: Prepare inventory
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
  - name: Loop over host_vars yaml files
    include: files/add_host_loop.yaml filename="{{ item }}"
    with_fileglob: "host_vars/*.yaml"

- name: Create & load configurations
  hosts: dc
  gather_facts: no
  connection: local

  tasks:
  - name: Assign temp folder to host
    set_fact:
      host_tmpdir: "{{ conf_dir }}/{{ inventory_hostname }}"
    changed_when: no
    check_mode: no

  - name: Make sure there are no remains from a previous run
    file:
      path: "{{ host_tmpdir }}"
      state: absent
    changed_when: no
    check_mode: no

  - name: Create tmp folder to store configs & diffs
    file:
      path: "{{ host_tmpdir }}"
      state: directory
    changed_when: no
    check_mode: no

  - name: Create configuration
    template:
      src: "{{ napalm_network_os }}/base.j2"
      dest: "{{ host_tmpdir }}/base.conf"
    changed_when: no
    check_mode: no

  - name: Load configuration into the device
    napalm_install_config:
      hostname: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      dev_os: "{{ napalm_network_os }}"
      config_file: "{{ host_tmpdir }}/base.conf"
      commit_changes: "{{ not ansible_check_mode }}"
      replace_config: false
